services:
  app:
    build:
      context: ..
    container_name: travel_agency_staging
    ports:
      - "3001:3000"
    expose:
      - "3001"
    env_file:
      - ../.env.staging
    volumes:
      - .:/app
    networks:
      - redestinea-staging
    restart: always

networks:
  default:
    name: redestinea-staging
  redestinea-staging:
    driver: bridge
