services:
  app:
    build:
      context: ..
    container_name: travel_agency_staging
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - ../.env.staging
    volumes:
      - .:/app
    networks:
      - redestinea-staging
    restart: always

  nginx:
    image: nginx:stable
    container_name: travel_agency_staging_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.staging.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/staging.redestinea.com:/etc/letsencrypt/live/staging.redestinea.com:ro
      - /etc/letsencrypt/archive/staging.redestinea.com:/etc/letsencrypt/archive/staging.redestinea.com:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
    networks:
      - redestinea-staging
    depends_on:
      - app
    restart: always
networks:
  default:
    name: redestinea-staging
  redestinea-staging:
    driver: bridge
